<?php
echo '[{
    "imgurl":"img/ca2.jpg",
    "cont":"飞驰人生",
    "pingfen":"8.9"
    },{
    "imgurl":"img/ca2.jpg",
    "cont":"飞驰人生",
    "pingfen":"8.9"
    },{
    "imgurl":"img/ca2.jpg",
    "cont":"飞驰人生",
    "pingfen":"8.9"
    },{
    "imgurl":"img/ca2.jpg",
    "cont":"飞驰人生",
    "pingfen":"8.9"
    },{
   "imgurl":"img/ca2.jpg",
   "cont":"飞驰人生",
   "pingfen":"8.9"
    },{
   "imgurl":"img/ca2.jpg",
   "cont":"飞驰人生",
   "pingfen":"8.9"
    },{
   "imgurl":"img/ca2.jpg",
   "cont":"飞驰人生",
   "pingfen":"8.9"
    },{
    "imgurl":"img/ca2.jpg",
    "cont":"飞驰人生",
    "pingfen":"8.9"
    }
]'
?>